CREATE TABLE `locations`(
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `latitude` VARCHAR(255) NOT NULL,
    `longitude` VARCHAR(255) NOT NULL,
    `image_name` VARCHAR(255) NOT NULL,
    `address` VARCHAR(255) NOT NULL,
    `house_count` BIGINT NOT NULL,
    `user_id` BIGINT UNSIGNED NOT NULL
);

CREATE TABLE `users`(
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `username` VARCHAR(255) NOT NULL,
    `email` VARCHAR(255) NOT NULL,
    `password` VARCHAR(255) NOT NULL
);
